### ISSUE TITLE
Does not work for Unbound-users

### ISSUE THREAD

**Issue by mweinelt** [flokli/mlarchive2maildir#6]
The archive uses some custom formatting: https://unbound.nlnetlabs.nl/pipermail/unbound-users/

mlarchive2maildir doesn't seem to find anything:
```
% ~/.local/bin/mlarchive2maildir -v DEBUG import https://unbound.nlnetlabs.nl/pipermail/unbound-users/ Unbound-users --list-id "Unbound users discussion list <unbound-users.unbound.net>" --reply-to "unbound-users@unbound.net"                          
debug: Querying https://unbound.nlnetlabs.nl/pipermail/unbound-users/ for mbox urls
debug: Starting new HTTPS connection (1): unbound.nlnetlabs.nl
debug: https://unbound.nlnetlabs.nl:443 "GET /pipermail/unbound-users/ HTTP/1.1" 200 49184
  [####################################]  100%
```

**Comment by mweinelt** [comment]
They don't expose the .gz file as a link, but it is there nevertheless. I bypassed the issue by assuming it's there and getting month and year from the thread link.

```diff
diff --git a/mlarchive2maildir/pipermail.py b/mlarchive2maildir/pipermail.py
index d8ce8b3..e4b089a 100644
--- a/mlarchive2maildir/pipermail.py
+++ b/mlarchive2maildir/pipermail.py
@@ -7,5 +7,5 @@ def get_mbox_urls(url):
     r = requests.get(url)
     soup = BeautifulSoup(r.text, 'html.parser')
     for link in soup.find_all('a'):
-        if 'Text' in link.text:
-            yield '{}/{}'.format(url, link.get('href'))
\ No newline at end of file
+        if 'Thread' in link.text:
+            yield '{}/{}.txt.gz'.format(url, link.get('href').split('/')[0])
\ No newline at end of file
```

**Comment by flokli** [comment]
Hm, not sure if there's much that should be done from `mlarchive2maildir` itself.

Technically, there's no link to the mbox files itself being shown, so we can't assume they're there (and I'm not very inclined just guessing).

However, it's already now possible to invoke `mlarchive2maildir` just with the path to each `.txt` or `.txt.gz`, so you can simply invoke it multiple times with the direct link to a monthly archive.
